# Generated by Django 4.2.5 on 2023-10-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=120)),
                ('image', models.CharField(max_length=120)),
                ('driver_name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
