# Generated by Django 4.2.5 on 2023-10-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='gender',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='todo',
            name='route',
            field=models.CharField(default='', max_length=120),
        ),
    ]
