# Generated by Django 4.2.5 on 2023-10-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westside', '0002_todo_gender_todo_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='driver_contact',
            field=models.IntegerField(default=0),
        ),
    ]
