# Generated by Django 4.2.5 on 2023-10-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westside', '0003_todo_driver_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
