# Generated by Django 4.2.5 on 2023-10-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('westside', '0005_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='confirm_password',
            new_name='password_confirmaion',
        ),
    ]
