# Generated by Django 4.2.5 on 2023-10-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('westside', '0006_rename_confirm_password_users_password_confirmaion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Staff',
        ),
    ]
