# Generated by Django 4.2.5 on 2023-10-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('westside', '0007_rename_users_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='password_confirmaion',
            new_name='password_confirmation',
        ),
    ]
