# Generated by Django 4.2.5 on 2023-10-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westside', '0008_rename_password_confirmaion_staff_password_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
