# Generated by Django 4.2.5 on 2023-10-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westside', '0009_alter_todo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
